dist: trusty
sudo: required
language: node_js

node_js:
  - "6"

os:
  - linux

addons:
  jwt:
    secure: "D9LsbX3nHLl55MXrXdLv6sJse7vEsUTHyxxxJlLwOxSUrlOLuhyE0DrvUVVvOvNjHbwgenmqdGFtQ8Gsx9q+C1psM/VtMoiEViLkxFzczAlElNqoD5nGM9/988aFzaipzvce13m5CjCaEjdZmUepc3JVgY5jFyW949JVOPLY7lZMu6jJgDXX//xZ6SqCZ+y0GSz/zE7nN8VhMceg7/elLeW63A8mROXGfwe4plssQ3JP6QoxlqBeaS97zRytX6b10oaAddtNpuHG53hIa/ZYGIfLvuVKKhdY3WhuuwF9m4/h+xgMbMjAuj1yoFdQ/2TCeORIV2/osuvkVHqZnmge523+endbnOzkaIb1q67v/t6tJ9gHrTz+8lM6Dj3A9Wj129x1fDsrEJOH74e0q+NvO0Qqz8YXLuwbh2boQYhUsgOhsFZ+MdMONa7+bqNUkX8IYyb1Xfj7WgLcuFn0RhwtTIhLFDwDWOBLhmdcvZPGbU3RrGS4m53wq/ZlMzDpwU8eFT+2s1BpYrnLFrTh9kJrL61KycvJgG7xPgS7g64rLFdtyV0wXVBqZ3XdiVzlARG9XABbCHAePPXJV6ggFPThLkU8ZKlgSc/eOTQY30lSrXj/8ws3+/pzgyzypy0Mm10LwkGmL5pBlQsT4q18l9Aj9WvzBzZbiJPukBgw5Rm9bpU="

env:
  global:
  - LOGS_DIR=/tmp/ngx-mime-build/logs
  - BROWSER_PROVIDER_READY_FILE=/tmp/ngx-mime-build/readyfile

before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

install:
  - npm install

before_script:
 - mkdir -p $LOGS_DIR
 - chmod +x ./scripts/ci/build-and-test.sh
 - chmod +x ./scripts/ci/publish-artifacts.sh
 - chmod +x ./scripts/deploy/publish-build-artifacts.sh
 - chmod +x ./scripts/saucelabs/start-tunnel.sh
 - chmod +x ./scripts/saucelabs/wait-tunnel.sh
 - chmod +x ./scripts/saucelabs/stop-tunnel.sh

script:
  - ./scripts/ci/build-and-test.sh

before_deploy:
  - cd dist

deploy:
  provider: npm
  api_key:
    secure: "LT3SjCFTj73BhRDWbkZltyrSN+HJ25nkNpgpg0MNUARiWZP9EKp96Xn8sciyQVsVCauZR5Msjb6CSH4icLeYq9wC96M5z3isI/svfs1YiMR1PZOLHY/AjDp4pNP8dur0dybY0NLINumhgGQPq9MBGbdracSt5amQaL9m+rBq1DQvOeiuSKsPrH5JfnXarDQKH2b2Ctvv4YqrsN+8+PlLskaY5Q1E5lY8E/4zVIVHF2OlM5UFmuST+7UvGycaKDHXmv05Ru7hsYZVExZ6LZaWILtBEOBAg/PcCxa0HmbQFnLEmkY4eLnH/TaWKzaL65T+WKRz+K9AVyESPyEU1NMVNqKqU1Z01KOpwMrqm5r7fQ66u6men6zStfy50wAYeyipKyeLXEZZ+6u7pI/QCPwj/S+XMTXnxqmn8+GRTBoZ5rJvJy+ss3N0UL1eN7KvxS/5gp6I39L5uv1vD0I3ZPIo7GvvtmKd1WRSrCc7KhMJfSGmy9BkBaPZ1LWXEK/0kqnhIB613dgbi8tv/JTLuOPx380GByQCwluJtcBWUsHhMOmrndN7+t0aPb1L69FYiHyX5Mdx2eFqKy4gzu5roU2UoINAM09PoDMGzdTFxGTMW2Bvq5wvWOFr3uLswC1iYTiJeslInl+xn7Xmv0csXPNgnerka5kLMO1qUulPJ9h67rE="
  skip_cleanup: true
  on:
    branch: master
    tags: true